### ISSUE TITLE
Presentation of extracted tabular data

### ISSUE THREAD

**Issue by rodricios** [libextract/libextract#10]
Currently, one of the possible, human readable way of viewing the extracted "tables", one should do the following: 

```python
from libextract import extract
from libextract.strategies import TABULAR
from libextract.html.tabular import filter_tags

from lxml.html import open_in_browser
from requests import get

reddit = get("http://reddit.com")
strat = TABULAR + (filter_tags,)

tabs = extract(reddit.content, strategy=strat)
tabs = list(tabs)
open_in_browser(tabs[0])
```

Any other ideas on how else we should present it? 

Edit: one very cool way is following import.io's approach as an [example](https://magic.import.io/?site=http:%2F%2Fwww.ikea.com%2Fus%2Fen%2Fsearch%2F%3Fquery%3Dchair); this means classifying by the node's "class" values.

**Comment by eugene-eeo** [comment]
I think we should just leave the presentation layer to the user. IMHO this is not the job of a library.

**Comment by rodricios** [comment]
Gotcha, but arguably, the ARTICLE_TEXT is a presentation-layer method. Should we provide the same text-type output for tabular extraction? 

This may also help "selling" the library as an extraction tool, as I don't think it's convincing enough to just say, "hey, here's the most frequent tag." 

It could even be a simple conversion of the html-node parameters to json:

```
{ 
  "tag": "div", 
  "class": "table-data",
  "inner_text": "blah blah blah" 
  ...
}
```

**Comment by eugene-eeo** [comment]
Sorry for the late reply, I was having lunch. Arguably this should live in a separate repository, perhaps **libextract/json-driver**? Also I think that the html-node parameters should include the XPath:

```json
{
  "tag": "div",
  "xpath": "//body/div",
  "class": "table-data"
}
```

It will also make it possible for users to develop their own "drivers" for libextract, such as their own custom XML format.

**Comment by rodricios** [comment]
It's all good! It should be me apologizing about my response times :P 

Or **libextract/formatters**? As those are end-of-the-pipeline functions, we could do something like:

```python
from libextract.formatter import article_text, tabular_json
...
text = article_text(extract(...))

json = tabular_json(extract(...))
```

Something prettier would be much better. 

You are correct though in that this idea should probably towards the end of the priority list.

**Comment by eugene-eeo** [comment]
:+1: formatters sound better. Again I'm not too sure of what to include in the json-formatted node. Any ideas?

**Comment by rodricios** [comment]
Hmm. Should this be a new repo or just a submodule? B/c as of now, we only have like two or three functions we'll be including in there :P

**Comment by eugene-eeo** [comment]
IMHO, better to make it a separate repo as we don't have to re-release the library when we make changes or make bugfixes to the formatters. Or we could just include a submodule like what you suggest as it will cut down the dependencies.

**Comment by rodricios** [comment]
Interesting point on the rerelease. Go ahead and make the repo then :)

**Comment by eugene-eeo** [comment]
@rodricios check it out: https://github.com/libextract/formatters

**Comment by rodricios** [comment]
Awesome! Great job!
