### ISSUE TITLE
README demo has 2 broken lines

### ISSUE THREAD

**Issue by ianozsvald** [libextract/libextract#12]
In `README` there are two problems:

```tabs = extract(reddit.content, strategy=TABULAR))``` has trailing second closing brace (just remove it)

```open_in_browser(tabs[0])``` where `open_in_browser` isn't defined and `tabs` isn't not scriptable (it is a generator)

**Comment by eugene-eeo** [comment]
@ianozsvald thanks! It seems to work now. Would you mind giving your two cents at #1 and #11? I'm quite stuck on those.

**Comment by ianozsvald** [comment]
Much obliged :-) Will try to take a look at the others, time permitting. I've linked libextract on my blog after a related talk at PyDataParis last week, cheers!
http://ianozsvald.com/2015/04/03/pydataparis-2015-and-cleaning-confused-collections-of-characters/

**Comment by eugene-eeo** [comment]
Thanks so much for linking our project! Do hop by in the future to see how we have grown!

**Comment by rodricios** [comment]
@ianozsvald, thanks!
