### ISSUE TITLE
Import error's for 2.x & 3.x

### ISSUE THREAD

**Issue by rodricios** [libextract/libextract#13]
``from libextract.html import parse_html`` is broken in python 2.7.8, and ``from .html import parse_html`` is broken for 3.4x (going from memory so I may be incorrect in exact version/statement). 

The change is addressed in [PEP 328](https://www.python.org/dev/peps/pep-0328/). Trying out solutions now.

**Comment by eugene-eeo** [comment]
It works perfectly in the unit tests?

**Comment by rodricios** [comment]
Nope, not in my tests :\

**Comment by eugene-eeo** [comment]
Did you sync your branch to the latest build though?

**Comment by rodricios** [comment]
I synced it maybe 5 minutes ago. I'm on the formatters branch

**Comment by eugene-eeo** [comment]
No problems here. Python 3.4.3 and 2.7.9 used.

**Comment by rodricios** [comment]
[pic](http://i.imgur.com/BbuT6mR.png)

**Comment by eugene-eeo** [comment]
Did you use nosetests or ``python setup.py test``? I had no troubles with both, the last time we had a similar problem was when the ``html`` submodule wasn't indexed.

**Comment by rodricios** [comment]
``python setup.py test``

Ok, so ``from __future__ import absolute_import`` does the trick for, I'm guessing, versions < 2.7.9

**Comment by eugene-eeo** [comment]
Man but that would be ugly... Let's just use relative imports? Do they work on Python 3.x?

**Comment by rodricios** [comment]
Doesn't look like it :/ 

[Quote](https://www.python.org/dev/peps/pep-0328/#timeline): 

In Python 2.5, you must enable the new absolute import behavior with 

    from __future__ import absolute_import

**Comment by eugene-eeo** [comment]
All relative imports then.

**Comment by rodricios** [comment]
And no 3.x support?

**Comment by eugene-eeo** [comment]
Ok I think I found the solution: http://stackoverflow.com/questions/5811463/when-to-use-absolute-imports

**Comment by rodricios** [comment]
Sorry, reading this now. In between classes :P

**Comment by rodricios** [comment]
Ok, sounds good! Did you have that ready to push?

**Comment by eugene-eeo** [comment]
I thought you were implementing it? I can't test it locally.

**Comment by rodricios** [comment]
haha, that's right, I got :)

**Comment by eugene-eeo** [comment]
Alright I'll work on this if it's not resolved tomorrow (or today). It's like 2 o'clock here and I need to get some sleep time.

**Comment by rodricios** [comment]
Please do get rest lol! It's 11 a.m. where I'm at. I'll try to handle this, but just fyi, if the approach you linked doesn't work, I'm opting for the __future__ statement. Unless prettyness is worth not including users with versions < 2.7.9

**Comment by rodricios** [comment]
Welp. So first, the answer you provided [here](http://stackoverflow.com/a/5811548) has a response below it saying: 

> As of September 213, this answer is wrong because PEP8 has changed. For example: "However, explicit relative imports are an acceptable alternative to absolute imports, especially when dealing with complex package layouts where using absolute imports would be unnecessarily verbose" 

Second, there is another, even more [unattractive solution](http://stackoverflow.com/a/4284378), imo.

Going with the \__future\__ statement :P Not very happy about it though lol

**Comment by rodricios** [comment]
#0405e34cdd1cb0ea82b6ddc71f3932e0fe9b5fd4
