### ISSUE TITLE
ImportError: No module named html

### ISSUE THREAD

**Issue by rodricios** [libextract/libextract#3]
Getting import error on Windows8 mingw32 when importing libextract in python shell. 

```
>>> import libextract
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "libextract\__init__.py", line 1, in <module>
    from libextract.html import STRATEGY
ImportError: No module named html
```

**Comment by rodricios** [comment]
fixed in 9bec99bb6a8ee6b04fd48da6afdb967292687b52.

**Comment by ianozsvald** [comment]
I've just installed today from head (using `git clone`) and I get a similar error:
```
Python 3.4.3 |Anaconda 2.1.0 (64-bit)| (default, Mar  6 2015, 12:03:53) 
Type "copyright", "credits" or "license" for more information.
...
IPython 3.0.0 -- An enhanced Interactive Python.
In [1]: import libextract
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-6c9f97f9c2a1> in <module>()
----> 1 import libextract

/home/ian/anaconda/envs/scratch/lib/python3.4/site-packages/libextract-0.0.0-py3.4.egg/libextract/__init__.py in <module>()
      6 from functools import partial
      7 from chardet import detect
----> 8 from .html import parse_html
      9 from .coretools import pipeline
     10 from .strategies import ARTICLE_TEXT

ImportError: No module named 'libextract.html'
```

The same bug is caused using your demo code in the README with ```from libextract import extract``` or ```from libextract.strategies import ARTICLE_NODE```.

I'm using Python 3.4, Linux (Mint 17.1), I installed from a git clone and then used `python setup.py install`.

**Comment by eugene-eeo** [comment]
@ianozsvald try out the latest build c4e2cc2, it should solve the bugs. Turns out that the ``html`` subpackage wasn't included in the list.

**Comment by ianozsvald** [comment]
Huzzah! Super quick fix, thanks :-) Most of your demo works in the README, I'll file another bug for that :-)
