### ISSUE TITLE
Move tests to separate directory?

### ISSUE THREAD

**Issue by eugene-eeo** [libextract/libextract#5]
I have mixed feelings when we put tests and the code under the lib directory. This means that when distributing our package and when users download it, they will download the entire test suite which contains the large files found in ``assets``. While this may be convenient for say developers who want to contribute to the library, it is not often the case. Most of the time if they want to contribute we just fork the repo. Also it makes it harder to run tests and we need to include our own ``__main__.py`` file, or rely on a test runner such as ``nose``.

See: http://stackoverflow.com/a/22704148
Also I look up to the [flask](https://github.com/mitsuhiko/flask) repository for examples and best practices.

cc @rodricios

**Comment by rodricios** [comment]
Fine by me :) I was referring to this [guide](http://www.scotttorborg.com/python-packaging/testing.html) but was still questioning whether or not to include the tests like that.
