### ISSUE TITLE
Bug in algo. Currently extracting all text in HTML. 

### ISSUE THREAD

**Issue by rodricios** [libextract/libextract#6]
Run tests and refer to the change in tests/assets/full_of_foos.html to see what I mean. I believe the bug arises in the pipeline, between get_pairs and argmax.

**Comment by eugene-eeo** [comment]
The problem was that the XPath selector I used selected every node, not just those with non-empty text nodes, as I didn't include ``[normalize-space()]``.

**Comment by rodricios** [comment]
Good job! I was trying to fix it, but luckily I checked your progress on this issue, b/c Idk what the heck I was trying to do haha.
