### ISSUE TITLE
Mission statement: "[libextract] provides composable, small functions [..]"

### ISSUE THREAD

**Issue by rodricios** [libextract/libextract#9]
"[..] that can be piped together to process the HT/XML document."

I'd like to put into writing that I think we should not only stick to that mantra (or mission statement?), but also officialize it as this project's description. 

With that in mind, I think we're reaching a point (or we've reached it already ref: 953c384b3cb1d8ae06f654f893c44e82cc74c835) where the lack of naming/functional-method conventions will delay the progress of this project. 

There's a few observations I should state:

1. Perfect extraction is impossible (this one is here for reasons I'll address in another issue/post)
2. Lambda functions are easy for the initiated, difficult for those not.
3. The "composable, small functions" we provide in html.py (we should probably rename that file, if we continue to add more functions) can be, to an extent, rewritten as a series of "pipelined" lambda functions. 
4. Without some set of protocols, the typical user will not be able to simply pick up this library and compose an effective "strategy"

To stress the problem of point 4, consider the following two extraction cases:

```python
article_strategy = (get_etree, get_pairs, histogram, argmax, get_final_text)

tabular_strategy = (get_etree, get_node_children_pairs, filter_node_children_pairs)
```

First, "get_etree", while I'm for keeping method names that describe the action and the returned structure, I believe we should opt for something closer to "parse" or "parse_html". Not only is it interpretable by most users of lxml.html and the nlp folks (ie. sentence parsing), but it's also, imo, a more concise statement. 

Second, as is evidenced in the definitions of *get_pairs* and *get_node_children_pairs*, we're doing a lot of *pair getting*. 

In both types of pairs returned, it's of the format **(HtmlElement, n-dimensional measurement)**. 

Just for completeness, in *get_pairs* we have **(HtmlElement, int)** and in get_node_children_pairs we have **(HtmlElement,** [Counter(key=**HtmlElement**, value=**int*(frequency*))**

Up until that point, our pipeline's flow of logic, and the names of the methods, matched up nicely. But after that, *histogram*, *argmax*, *get_final_text* and *filter_node_children_pairs* are inelegantly non-synergistic, for lack of a better term. 

I don't know if it's too early in the project to be concerned about this, but I think this project will likely head towards a dead end if there isn't some proper set of ground rules. Sorry for the pessimism :(

I'll work on refactoring the code I've commited in 953c384b3cb1d8ae06f654f893c44e82cc74c835, and see if I can come up with something more constructive than the above.

**Comment by eugene-eeo** [comment]
I think we should separate the functions in the ``html`` module to a directory. The common functions will be placed in ``html.commons`` and the specific ones can be placed in ``html.tabular`` and ``html.text``.

About generic functions- although I am all for modularity and composability, I believe that overly generic functions should be avoided and replaced with specific functions to improve performance and also understanding. Pipelining allows us to do this because the transformer functions are small and have simple logic.

**Comment by eugene-eeo** [comment]
I have refactored tabular extraction, checkout the ``tabular-refactor`` branch. Is this the desired result? Note that you only see 5 (probably) tabular nodes because I have set the default sorting limit to 5. See [html.tabular](https://github.com/libextract/libextract/blob/tabular-refactor/libextract/html/tabular.py#L39) on how this is implemented.

```python
>>> from requests import get
>>> reddit = get('http://reddit.com')
>>> tabs = extract(reddit.content, strategy=TABULAR)
>>> tabs
[(<Element div at 0x10e3f2ec0>, [('a', 51)]),
 (<Element div at 0x10e0d75d0>, [('div', 51)]),
 (<Element ul at 0x10e41b4c8>, [('li', 48)]),
 (<Element div at 0x10e0cf1b0>, [('div', 23)]),
 (<Element head at 0x10e3f2368>, [('link', 8)])]
```

**Comment by rodricios** [comment]
That looks great! Let's go ahead and merge (rebase?) the changes.

**Comment by eugene-eeo** [comment]
Merged, do you want me to merge into master as well?

**Comment by rodricios** [comment]
I have some updates I'd like to add first, I'll update soon:)

**Comment by eugene-eeo** [comment]
I'll assume this issue is settled and close it.
